### ISSUE TITLE
武器の値の自動設定について

### ISSUE THREAD

**Issue by y-chan** [PGseatake/GenshinImpactDamageEmulator#1]
こんにちは、いつも利用させていただいています。

武器の値が自動設定されない(していない)件について、Issueを起票させていただきます。
私の調べでは武器の基礎攻撃力はレアリティごとに固定値が使われているようで、それらを`param.ts`に追加し、攻撃力の初期値とレアリティから自動で値を算出するようにすることでより簡単に利用できるようになるかなと考えています。
また、サブステータスについても、レアリティごとに初期値から一定倍率で増えるようになっているようです。
(キャラの天賦ダメージスケールと同じ感じですね。この倍率、良く調べたなぁと思い感心しておりました)
https://github.com/PGseatake/GenshinImpactDamageEmulator/blob/ae16f0942906d34eba5b882119076f33d1f5b330/src/ts/param.ts#L638-L642

出来ればPull Requestsを提出したいのですが、あいにく私はそこまでJSやTSに精通していないので、すぐには対応できません。また、管理者さんの意向もあると思いますので、Issueに留めておきました。
対応の方針についてだけでもお聞かせいただければなと思います。よろしくお願いします。

**Comment by PGseatake** [comment]
いつもご利用ありがとうございますm(_ _)m

> 私の調べでは武器の基礎攻撃力はレアリティごとに固定値が使われているようで、それらをparam.tsに追加し、攻撃力の初期値とレアリティから自動で値を算出するようにすることでより簡単に利用できるようになるかなと考えています。
> また、サブステータスについても、レアリティごとに初期値から一定倍率で増えるようになっているようです。

固定値であることは把握しているのですが、他の機能実装を優先していて、実装保留している状態です。

> また、管理者さんの意向もあると思いますので、Issueに留めておきました。

お気遣いありがとうございます！（ありがた過ぎて骨の髄まで沁みました）

> 対応の方針についてだけでもお聞かせいただければなと思います。

後々実装する予定なので、今しばらくお待ち頂けると助かります。

**Comment by y-chan** [comment]
了解しました、気長に待ちます！

**Comment by PGseatake** [comment]
先週と今日の更新で、Issueの対応完了しました。
このIssueはクローズしますm(_ _)m
